# Generated by Django 5.1.1 on 2024-09-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name=4)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('trans', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('C', 'CVT')], max_length=1)),
                ('epa', models.IntegerField()),
                ('engine', models.CharField(max_length=250)),
                ('intColor', models.CharField(max_length=25)),
                ('extColor', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
    ]
