# Generated by Django 5.1.1 on 2024-09-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0007_mod_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
